// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbjbanrddaneuosqgnls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiamJhbnJkZGFuZXVvc3FnbmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjU4NTIsImV4cCI6MjA2MDIwMTg1Mn0.fiLNm9h9sZ_35E9EbfvmrwY_J5SYjie5CjYRg2v40A4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);